pipeline {
    agent any

    tools {
        jdk 'JDK21'
        maven 'Maven-3.9.9'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/MojjadaCode-Git/simple-java-maven-app.git'
            }
        }

        stage('Clean Workspace') {
            steps {
                echo "Cleaning old build files..."
                sh 'rm -rf target'
            }
        }

        stage('Build') {
            steps {
                echo "Building project..."
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                echo "Running tests..."
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                echo "Packaging application..."
                sh 'mvn package'
            }
            post {
                success {
                    archiveArtifacts artifacts: '**/target/*.war', fingerprint: true
                }
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                echo "Deploying WAR to Tomcat..."
                sh '''
                    # remove old WAR
                    sudo rm -rf /opt/tomcat/webapps/my-app*

                    # copy new WAR
                    sudo cp target/*.war /opt/tomcat/webapps/my-app.war

                    # restart tomcat
                    sudo systemctl restart tomcat
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Build + Deploy succeeded!"
            echo "Access app at: http://100.26.175.123:8081/my-app/"
        }
        failure {
            echo "❌ Build failed. Please check console output."
        }
    }
}
